version: '3.8'
#libfontenc1 xfonts-75dpi xfonts-base xfonts-encodings xfonts-utils
services:
  mysql:
    image: mysql
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - '3383:3306'
  php:
    image: "php8.3-local:1.0"
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /app
    depends_on:
      - mysql
    links:
      - mysql:mysql
    ports:
      #- '8086:80'
      - '9003:80'
    #  - '9004:443'
    volumes:
      - ./:/app
      - ./docker/apache/default.conf:/etc/apache2/sites-available/000-default.conf
      - ./bin/console:/usr/bin/app-console
  adminer:
    image: adminer
    restart: always
    ports:
      - '8686:8080'

