services:
  db:
    image: mysql:8.0
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    env_file:
      - .env
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DATABASE_USER}", "-p${DATABASE_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  php:
    build:
      context: ./docker
    container_name: contrato-online-php
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./:/app
      - var_data:/app/var
      - certs_data:/app/config/certs
      - ./bin/console:/usr/bin/app-console
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "php -r 'echo 1;' > /dev/null 2>&1" ]
      interval: 5s
      timeout: 5s
      retries: 30

  nginx:
    image: nginx:stable-alpine
    depends_on:
      php:
        condition: service_healthy
    ports:
      - '127.0.0.1:9004:80'
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/app:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  var_data:
  certs_data:
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - '8686:8080'
