version: '3.8'
#libfontenc1 xfonts-75dpi xfonts-base xfonts-encodings xfonts-utils
services:
  mysql:
    image: mysql
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
#    ports:
#      - '3383:3306'
  php:
    build: ./docker
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /app
    depends_on:
      - mysql
    ports:
      - '9003:80'
     # - '9004:443'
    volumes:
      - ./:/app
      - ./docker/apache/default.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/supervisor.d/messenger-scheduler.conf:/etc/supervisor/conf.d/messenger-scheduler.conf
      - ./docker/supervisor.d/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./bin/console:/usr/bin/app-console
    #entrypoint: [ "/usr/local/bin/start-supervisord.sh" ]
    restart: unless-stopped




